version: "3.8"

services:
  db:
    image: postgres:13
    volume:
      - postgres_data:/var/lib/postgres/data
    environment:
      POSTGRES_DB: dockerproject
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: d

  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    enviornments:
      SECRET_KEY: django-insecure-cvee$id%hz%+(0twb*b@2vqz@xr)^@_j=4f+s8_3t$a2f&zvlm
      DEBUG:
